version: "3.7"

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
    volumes:
     - ./:/app
   
    
  postgres:
   container_name: postgres
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: fastapi_starter
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   volumes:
     - postgres-data:/var/lib/postgresql/data

volumes:
 postgres-data: